// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/message_type.proto

package org.codetome.riptide.protobuf;

/**
 * Protobuf enum {@code data.MessageType}
 */
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SIMPLE_MESSAGE = 0;</code>
   */
  SIMPLE_MESSAGE(0),
  /**
   * <code>PROCESS_FINISHING_MESSAGE = 1;</code>
   */
  PROCESS_FINISHING_MESSAGE(1),
  /**
   * <code>PROCESS_STARTING_MESSAGE = 2;</code>
   */
  PROCESS_STARTING_MESSAGE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SIMPLE_MESSAGE = 0;</code>
   */
  public static final int SIMPLE_MESSAGE_VALUE = 0;
  /**
   * <code>PROCESS_FINISHING_MESSAGE = 1;</code>
   */
  public static final int PROCESS_FINISHING_MESSAGE_VALUE = 1;
  /**
   * <code>PROCESS_STARTING_MESSAGE = 2;</code>
   */
  public static final int PROCESS_STARTING_MESSAGE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return SIMPLE_MESSAGE;
      case 1: return PROCESS_FINISHING_MESSAGE;
      case 2: return PROCESS_STARTING_MESSAGE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.codetome.riptide.protobuf.MessageTypeOuterClass.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:data.MessageType)
}

