// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/message_type.proto

package org.codetome.riptide.protobuf;

public final class MessageTypeOuterClass {
  private MessageTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027data/message_type.proto\022\004data*^\n\013Messa" +
      "geType\022\022\n\016SIMPLE_MESSAGE\020\000\022\035\n\031PROCESS_FI" +
      "NISHING_MESSAGE\020\001\022\034\n\030PROCESS_STARTING_ME" +
      "SSAGE\020\002B#\n\035org.codetome.riptide.protobuf" +
      "H\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
