// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/protobuf_payload_kind.proto

package org.codetome.riptide.protobuf;

/**
 * Protobuf enum {@code data.PayloadKind}
 */
public enum PayloadKind
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>JSON = 0;</code>
   */
  JSON(0),
  /**
   * <code>PROTOBUF = 1;</code>
   */
  PROTOBUF(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>JSON = 0;</code>
   */
  public static final int JSON_VALUE = 0;
  /**
   * <code>PROTOBUF = 1;</code>
   */
  public static final int PROTOBUF_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PayloadKind valueOf(int value) {
    return forNumber(value);
  }

  public static PayloadKind forNumber(int value) {
    switch (value) {
      case 0: return JSON;
      case 1: return PROTOBUF;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PayloadKind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PayloadKind> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PayloadKind>() {
          public PayloadKind findValueByNumber(int number) {
            return PayloadKind.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.codetome.riptide.protobuf.PayloadKindOuterClass.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final PayloadKind[] VALUES = values();

  public static PayloadKind valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PayloadKind(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:data.PayloadKind)
}

