// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/process_state.proto

package org.codetome.riptide.protobuf;

public final class ProcessStateOuterClass {
  private ProcessStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030data/process_state.proto\022\004data*S\n\014Proc" +
      "essState\022\013\n\007STARTED\020\000\022\017\n\013IN_PROGRESS\020\001\022\n" +
      "\n\006FAILED\020\002\022\013\n\007ERRORED\020\003\022\014\n\010FINISHED\020\004B#\n" +
      "\035org.codetome.riptide.protobufH\001P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
