// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/process_state.proto

package org.codetome.riptide.protobuf;

/**
 * Protobuf enum {@code data.ProcessState}
 */
public enum ProcessState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>STARTED = 0;</code>
   */
  STARTED(0),
  /**
   * <code>IN_PROGRESS = 1;</code>
   */
  IN_PROGRESS(1),
  /**
   * <code>FAILED = 2;</code>
   */
  FAILED(2),
  /**
   * <code>ERRORED = 3;</code>
   */
  ERRORED(3),
  /**
   * <code>FINISHED = 4;</code>
   */
  FINISHED(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>STARTED = 0;</code>
   */
  public static final int STARTED_VALUE = 0;
  /**
   * <code>IN_PROGRESS = 1;</code>
   */
  public static final int IN_PROGRESS_VALUE = 1;
  /**
   * <code>FAILED = 2;</code>
   */
  public static final int FAILED_VALUE = 2;
  /**
   * <code>ERRORED = 3;</code>
   */
  public static final int ERRORED_VALUE = 3;
  /**
   * <code>FINISHED = 4;</code>
   */
  public static final int FINISHED_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProcessState valueOf(int value) {
    return forNumber(value);
  }

  public static ProcessState forNumber(int value) {
    switch (value) {
      case 0: return STARTED;
      case 1: return IN_PROGRESS;
      case 2: return FAILED;
      case 3: return ERRORED;
      case 4: return FINISHED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProcessState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProcessState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProcessState>() {
          public ProcessState findValueByNumber(int number) {
            return ProcessState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.codetome.riptide.protobuf.ProcessStateOuterClass.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final ProcessState[] VALUES = values();

  public static ProcessState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ProcessState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:data.ProcessState)
}

