// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/reserved_groups.proto

package org.codetome.riptide.protobuf;

/**
 * Protobuf enum {@code data.ReservedGroups}
 */
public enum ReservedGroups
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DEFAULT_GROUP = 0;</code>
   */
  DEFAULT_GROUP(0),
  /**
   * <code>ALL_GROUPS = 1;</code>
   */
  ALL_GROUPS(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>DEFAULT_GROUP = 0;</code>
   */
  public static final int DEFAULT_GROUP_VALUE = 0;
  /**
   * <code>ALL_GROUPS = 1;</code>
   */
  public static final int ALL_GROUPS_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ReservedGroups valueOf(int value) {
    return forNumber(value);
  }

  public static ReservedGroups forNumber(int value) {
    switch (value) {
      case 0: return DEFAULT_GROUP;
      case 1: return ALL_GROUPS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ReservedGroups>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ReservedGroups> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ReservedGroups>() {
          public ReservedGroups findValueByNumber(int number) {
            return ReservedGroups.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.codetome.riptide.protobuf.ReservedGroupsOuterClass.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final ReservedGroups[] VALUES = values();

  public static ReservedGroups valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ReservedGroups(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:data.ReservedGroups)
}

