// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/reserved_versions.proto

package org.codetome.riptide.protobuf;

/**
 * Protobuf enum {@code data.ReservedVersions}
 */
public enum ReservedVersions
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DEFAULT_VERSION = 0;</code>
   */
  DEFAULT_VERSION(0),
  /**
   * <code>ALL_VERSIONS = 1;</code>
   */
  ALL_VERSIONS(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>DEFAULT_VERSION = 0;</code>
   */
  public static final int DEFAULT_VERSION_VALUE = 0;
  /**
   * <code>ALL_VERSIONS = 1;</code>
   */
  public static final int ALL_VERSIONS_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ReservedVersions valueOf(int value) {
    return forNumber(value);
  }

  public static ReservedVersions forNumber(int value) {
    switch (value) {
      case 0: return DEFAULT_VERSION;
      case 1: return ALL_VERSIONS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ReservedVersions>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ReservedVersions> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ReservedVersions>() {
          public ReservedVersions findValueByNumber(int number) {
            return ReservedVersions.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.codetome.riptide.protobuf.ReservedVersionsOuterClass.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final ReservedVersions[] VALUES = values();

  public static ReservedVersions valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ReservedVersions(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:data.ReservedVersions)
}

